const sequelize = require("./config/db");
const Hospital = require("./models/hospital");
const Psychiatrist = require("./models/psychiatrist");
const Patient = require("./models/patient");
const bcrypt = require("bcryptjs");

const seedDatabase = async () => {
  await sequelize.sync({ force: true });

  const hospitals = [
    { name: "Apollo Hospitals" },
    { name: "Jawaharlal Nehru Medical College and Hospital" },
    { name: "Indira Gandhi Institute of Medical Sciences (IGIMS)" },
    { name: "AIIMS - All India Institute Of Medical Science" },
  ];

  const hospitalInstances = await Hospital.bulkCreate(hospitals);

  const psychiatrists = [
    { name: "Dr. Priya Sharma", hospitalId: hospitalInstances[0].id },
    { name: "Dr. Rohit Kapoor", hospitalId: hospitalInstances[0].id },
    { name: "Dr. Sunita Verma", hospitalId: hospitalInstances[1].id },
    { name: "Dr. Vikram Patel", hospitalId: hospitalInstances[1].id },
    { name: "Dr. Anjali Mehta", hospitalId: hospitalInstances[2].id },
    { name: "Dr. Rajesh Gupta", hospitalId: hospitalInstances[2].id },
    { name: "Dr. Nisha Singh", hospitalId: hospitalInstances[3].id },
    { name: "Dr. Manoj Kumar", hospitalId: hospitalInstances[3].id },
  ];

  const psychiatristInstances = await Psychiatrist.bulkCreate(psychiatrists);

  const patients = [
    {
      name: "John Patient",
      address: "123 Street",
      email: "john.patient@example.com",
      phone: "+1234567890",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo1.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Jane Patient",
      address: "456 Avenue",
      email: "jane.patient@example.com",
      phone: "+1234567891",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo2.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Alice Brown",
      address: "789 Road",
      email: "alice.brown@example.com",
      phone: "+1234567892",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo3.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Bob White",
      address: "101 Blvd",
      email: "bob.white@example.com",
      phone: "+1234567893",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo4.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Charlie Black",
      address: "102 Street",
      email: "charlie.black@example.com",
      phone: "+1234567894",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo5.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Daisy Green",
      address: "103 Avenue",
      email: "daisy.green@example.com",
      phone: "+1234567895",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo6.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Edward Red",
      address: "104 Road",
      email: "edward.red@example.com",
      phone: "+1234567896",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo7.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Fiona Blue",
      address: "105 Blvd",
      email: "fiona.blue@example.com",
      phone: "+1234567897",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo8.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "George Yellow",
      address: "106 Street",
      email: "george.yellow@example.com",
      phone: "+1234567898",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo9.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Hannah Pink",
      address: "107 Avenue",
      email: "hannah.pink@example.com",
      phone: "+1234567899",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo10.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Ivy Orange",
      address: "108 Road",
      email: "ivy.orange@example.com",
      phone: "+1234567800",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo11.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Jack Purple",
      address: "109 Blvd",
      email: "jack.purple@example.com",
      phone: "+1234567801",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo12.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Katie Cyan",
      address: "110 Street",
      email: "katie.cyan@example.com",
      phone: "+1234567802",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo13.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Leo Magenta",
      address: "111 Avenue",
      email: "leo.magenta@example.com",
      phone: "+1234567803",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo14.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Mia Gray",
      address: "112 Road",
      email: "mia.gray@example.com",
      phone: "+1234567804",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo15.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Nina Lime",
      address: "113 Blvd",
      email: "nina.lime@example.com",
      phone: "+1234567805",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo16.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Oscar Maroon",
      address: "114 Street",
      email: "oscar.maroon@example.com",
      phone: "+1234567806",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo17.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Paula Gold",
      address: "115 Avenue",
      email: "paula.gold@example.com",
      phone: "+1234567807",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo18.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Quinn Silver",
      address: "116 Road",
      email: "quinn.silver@example.com",
      phone: "+1234567808",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo19.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Ruby Bronze",
      address: "117 Blvd",
      email: "ruby.bronze@example.com",
      phone: "+1234567809",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo20.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Steve Olive",
      address: "118 Street",
      email: "steve.olive@example.com",
      phone: "+1234567810",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo21.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Tina Navy",
      address: "119 Avenue",
      email: "tina.navy@example.com",
      phone: "+1234567811",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo22.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Uma Teal",
      address: "120 Road",
      email: "uma.teal@example.com",
      phone: "+1234567812",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo23.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Victor Peach",
      address: "121 Blvd",
      email: "victor.peach@example.com",
      phone: "+1234567813",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo24.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Wendy Plum",
      address: "122 Street",
      email: "wendy.plum@example.com",
      phone: "+1234567814",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo25.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Xander Indigo",
      address: "123 Avenue",
      email: "xander.indigo@example.com",
      phone: "+1234567815",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo26.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Yara Coral",
      address: "124 Road",
      email: "yara.coral@example.com",
      phone: "+1234567816",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo27.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Zack Azure",
      address: "125 Blvd",
      email: "zack.azure@example.com",
      phone: "+1234567817",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo28.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Amber Mint",
      address: "126 Street",
      email: "amber.mint@example.com",
      phone: "+1234567818",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo29.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Ben Mint",
      address: "127 Avenue",
      email: "ben.mint@example.com",
      phone: "+1234567819",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo30.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Cara Mint",
      address: "128 Road",
      email: "cara.mint@example.com",
      phone: "+1234567820",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo31.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Dan Mint",
      address: "129 Blvd",
      email: "dan.mint@example.com",
      phone: "+1234567821",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo32.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Ella Mint",
      address: "130 Street",
      email: "ella.mint@example.com",
      phone: "+1234567822",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo33.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Finn Mint",
      address: "131 Avenue",
      email: "finn.mint@example.com",
      phone: "+1234567823",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo34.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Grace Mint",
      address: "132 Road",
      email: "grace.mint@example.com",
      phone: "+1234567824",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo35.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Henry Mint",
      address: "133 Blvd",
      email: "henry.mint@example.com",
      phone: "+1234567825",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo36.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Isla Mint",
      address: "134 Street",
      email: "isla.mint@example.com",
      phone: "+1234567826",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo37.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Jack Mint",
      address: "135 Avenue",
      email: "jack.mint@example.com",
      phone: "+1234567827",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo38.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Kara Mint",
      address: "136 Road",
      email: "kara.mint@example.com",
      phone: "+1234567828",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo39.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Leo Mint",
      address: "137 Blvd",
      email: "leo.mint@example.com",
      phone: "+1234567829",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo40.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Mia Mint",
      address: "138 Street",
      email: "mia.mint@example.com",
      phone: "+1234567830",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo41.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Nina Mint",
      address: "139 Avenue",
      email: "nina.mint@example.com",
      phone: "+1234567831",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo42.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Omar Mint",
      address: "140 Road",
      email: "omar.mint@example.com",
      phone: "+1234567832",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo43.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Pia Mint",
      address: "141 Blvd",
      email: "pia.mint@example.com",
      phone: "+1234567833",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo44.jpg",
      psychiatristId: psychiatristInstances[1].id,
    },
    {
      name: "Quinn Mint",
      address: "142 Street",
      email: "quinn.mint@example.com",
      phone: "+1234567834",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo45.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Rita Mint",
      address: "143 Avenue",
      email: "rita.mint@example.com",
      phone: "+1234567835",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo46.jpg",
      psychiatristId: psychiatristInstances[2].id,
    },
    {
      name: "Sam Mint",
      address: "144 Road",
      email: "sam.mint@example.com",
      phone: "+1234567836",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo47.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Tina Mint",
      address: "145 Blvd",
      email: "tina.mint@example.com",
      phone: "+1234567837",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo48.jpg",
      psychiatristId: psychiatristInstances[3].id,
    },
    {
      name: "Uma Mint",
      address: "146 Street",
      email: "uma.mint@example.com",
      phone: "+1234567838",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo49.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
    {
      name: "Vic Mint",
      address: "147 Avenue",
      email: "vic.mint@example.com",
      phone: "+1234567839",
      password: await bcrypt.hash("Password1", 10),
      photo: "uploads/photo50.jpg",
      psychiatristId: psychiatristInstances[0].id,
    },
  ];

  await Patient.bulkCreate(patients);

  console.log("Database seeded");
};

seedDatabase()
  .catch((err) => {
    console.error("Failed to seed database:", err);
  })
  .finally(() => {
    sequelize.close();
  });
